In [1]:
import numpy as np
import pandas as pd
import datetime as dt
df=pd.read_csv('orders.csv')

In [2]:
df

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [4]:
df['date']=pd.to_datetime(df['date'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [6]:
df

          date  product_id  city_id  orders
0   2019-12-10        5628       25       3
1   2018-08-15        3646       14     157
2   2018-10-23        1859       25       1
3   2019-08-17        7292       25       1
4   2019-01-06        4344       25       3
..         ...         ...      ...     ...
995 2018-10-08         255       13       1
996 2018-12-06        5521        7       1
997 2019-05-07         487       26      14
998 2019-03-03        1503       21       2
999 2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [7]:
df['month']=df['date'].dt.month

In [8]:
df

          date  product_id  city_id  orders  month
0   2019-12-10        5628       25       3     12
1   2018-08-15        3646       14     157      8
2   2018-10-23        1859       25       1     10
3   2019-08-17        7292       25       1      8
4   2019-01-06        4344       25       3      1
..         ...         ...      ...     ...    ...
995 2018-10-08         255       13       1     10
996 2018-12-06        5521        7       1     12
997 2019-05-07         487       26      14      5
998 2019-03-03        1503       21       2      3
999 2019-10-15        6371        7      22     10

[1000 rows x 5 columns]

In [23]:
 df['day']=df['date'].dt.semester

AttributeError: 'DatetimeProperties' object has no attribute 'semester'

In [21]:
df

          date  product_id  city_id  orders  month        day
0   2019-12-10        5628       25       3     12    Tuesday
1   2018-08-15        3646       14     157      8  Wednesday
2   2018-10-23        1859       25       1     10    Tuesday
3   2019-08-17        7292       25       1      8   Saturday
4   2019-01-06        4344       25       3      1     Sunday
..         ...         ...      ...     ...    ...        ...
995 2018-10-08         255       13       1     10     Monday
996 2018-12-06        5521        7       1     12   Thursday
997 2019-05-07         487       26      14      5    Tuesday
998 2019-03-03        1503       21       2      3     Sunday
999 2019-10-15        6371        7      22     10    Tuesday

[1000 rows x 6 columns]

In [24]:
dt.datetime.today()

datetime.datetime(2025, 3, 26, 18, 23, 3, 438878)